### ISSUE TITLE
github (light) theme colors don't match 2025-08-29 colors used by GitHub.com

### ISSUE THREAD

**Issue by clach04** [tinted-theming/schemes#76]
Looking at https://github.com/tinted-theming/tinted-gallery/blob/main/build.sh via a web browser (with default light theme), it looks different to the preview available in the gallery at https://tinted-theming.github.io/tinted-gallery/

I've only checked github (the light one, not the dark one). At the very least a set of colors has been swapped.

I'm not using the GitHub scheme myself, I just noticed it when creating some sample preview screenshots in https://github.com/tinted-theming/base16-scintillua/tree/main/docs/images

### GitHub screenshot

From  https://github.com/tinted-theming/tinted-gallery/blob/main/build.sh

<img width="789" height="751" alt="Image" src="https://github.com/user-attachments/assets/38d9cbcb-1358-401e-81b8-e21b4abf42a3" />

### Tinted Gallery screenshot

from https://tinted-theming.github.io/tinted-gallery/ which states:

This gallery is generated from [tinted-theming/tinted-vim](https://github.com/tinted-theming/tinted-vim).

<img width="496" height="613" alt="Image" src="https://github.com/user-attachments/assets/37afe770-6fa4-41f1-9dbc-25ae56b191a8" />

Whilst Tinted Gallery claims this is derived from Base24, it looks like Bsae16 is also impacted:

  * https://github.com/tinted-theming/schemes/blob/spec-0.11/base24/github.yaml
  * https://github.com/tinted-theming/schemes/blob/spec-0.11/base16/github.yaml

**Comment by JamyGolden** [comment]
Hmm interesting. I think that bug is actually an issue with tinted-gallery itself and not with the scheme. When I filtered the schemes by variant and scrolled down to github light, it looked fine, but had the issue when I first looked at it.

**Comment by bezhermoso** [comment]
This can be closed now. This is fixed in the redesign.

**Comment by clach04** [comment]
@bezhermoso I'm not able to confirm this as resolved :-( 

I can't see any shell scripts to compare with any more (I can't locate the rust demos code used today which would be the obvious thing to compare with), so I went with diff as that is possible to see the differences with a few mouse clicks.

Open https://tinted-theming.github.io/tinted-gallery/
search/filter "github", set drop down to Diff.

<img width="1867" height="1099" alt="Image" src="https://github.com/user-attachments/assets/aea131fe-2822-4cba-9b32-2647e662a47d" />

Then compare with a random diff, e.g. https://github.com/tinted-theming/tinted-gallery/commit/f201af9cc0227d2b8118c2c9100f035787358ebe

<img width="1867" height="1099" alt="Image" src="https://github.com/user-attachments/assets/bd7666ce-6cac-4372-bf42-5fa1c3c0bbe0" />

**Comment by bezhermoso** [comment]
Re-opening this issue as this is indeed unresolved.

Two layers of fixes:

- Update the Github inspired themes to use the exact colors as those defined in https://github.com/primer/primitives: https://github.com/tinted-theming/schemes/pull/110. It also introduces variants to match what's available on Github e.g. high-contrast, dimmed, and colorblind variants.
- Update the gallery to highlight code snippets the way tinted-nvim does in higher fidelity: https://github.com/tinted-theming/tinty/pull/177

Note though that the scheme updates is primarily about parity with the official colors. However, tinted-nvim does not (and will not) match how Github highlights identical code. Perhaps that will be possible with a Tinted8 variant given that spec's semantics, but worth pointing out that we can be 100% parity with colors, but not necessarily in all the ways they are applied to the syntax tree.

**Comment by bezhermoso** [comment]
The gallery is now showing the updated GitHub themes as well as the new GitHub variants @clach04, see my note above regarding: highlighting parity vs code in GitHub.

**Comment by clach04** [comment]
@bezhermoso I'm still not sure how to compare, the original bug report used shell scripts to identify color mismatches. The new gallery doesn't mention shell scripts at all which was why I picked diff, it was the only one I could see to do a compare.

I can't locate the rust example (first example in the list tgat Gallery offers) to compare with, so I went ahead and copy/pasted the Rust Tinty code into a gist at https://gist.github.com/clach04/82b156c9282370edf93cb2717aa05e4c and it is closer but not the same. Black looks different and color choices for functions are different colors but that might be a theme rather than color issue. Screen shot in case it helps but as it's no longer possible to compare like before with shell scripts I'm not sure how to evaluate.

<img width="2121" height="1015" alt="Image" src="https://github.com/user-attachments/assets/5e611853-464c-434d-ab7e-1cec4637e886" />

Every color in the first line is different, so I'm assuming this is still broken? @JamyGolden thoughts? I think you use Rust and would know if this is a color versus scheme mapping issue.

The purple `with_base(16).build` doesn't look the same to my eyes (and used with different elements; `println` and `Some`)

I compared https://github.com/tinted-theming/tinted-gallery/blob/main/build.sh which still looks like the screenshot in the original report and it seems to visually match what I see in the new Rust gist https://gist.github.com/clach04/82b156c9282370edf93cb2717aa05e4c BUT I've only looked at purple and I've not sat and checked the hex RGB value.

Awesome to see so many new Github variants... so it's possible I'm not comparing the right one? Hopefully it's clear from the screenshot I'm using https://tinted-theming.github.io/tinted-gallery/#base16-github

**Comment by bezhermoso** [comment]
Some discoveries:

1. GitHub applies slight variance in PrettyLights (their syntax color palette) vs the base color palette in Primer (their design system).
2. The Primer palette makes a distinction between ANSI colors (for CLIs and emulators) and for code displays (PrettyLights). 

This makes Tinted8 the best candidate to follow Primer's palette with fidelity IMO. However, for Base16 and Base24, IMO the ANSI palette is the one to adopt, even though syntax highlighting will diverge from how code is actually displayed on GitHub.

**Comment by clach04** [comment]
Thanks for figuring this out @bezhermoso,  I know how tedious comparison can be. I'm pretty excited by tinted8 :-)
